version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: go_postgres
    environment:
      POSTGRES_USER: arifrizal
      POSTGRES_PASSWORD: buka1122
      POSTGRES_DB: go_rest_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arifrizal"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: